### ISSUE TITLE
Is it possible to call Binance Smart Chain?

### ISSUE THREAD

**Issue by ChurikiTenna** [Boilertalk/Web3.swift#105]
I am new to web3.
Sorry, If my question sound silly.

I was trying to init web3 with infura url, but apparently infura does not support BSC network.
So, I created Ankr api, and tried to get rpc url with Formatic to init web3.
But Formatic does not support iOS anymore (SDK on github is archived).

What should I do...??
I appreciate any help!

**Comment by Mreyna3** [comment]
Try using quick node to spin up a BSC node then connect via HTTP
