### ISSUE TITLE
Support for macOS 12.3.1

### ISSUE THREAD

**Issue by danil-z** [Boilertalk/Web3.swift#119]
It seems that library fails to build for macOS 12.3.1.
Any plans to support current Apple platforms?

**Comment by koraykoska** [comment]
What is the error?

**Comment by FrankSolleveld** [comment]
Do you mean that your current operating system is macOS 12.3.1? I'm on that OS as well and have an Apple silicon chip. Web3.swift fails on `EthereumQuantityTag.swift` with the following error:
`'BigUInt' is ambiguous for type lookup in this context`

**Comment by Florian-S-A-W** [comment]
I cannot reproduce this issue on macOS 12.6

**Comment by Florian-S-A-W** [comment]
This issue seems to have been fixed in more recent macOS releases.
