### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by emiliomarin** [Boilertalk/Web3.swift#13]
Hello, I'm tying to install this library in my project. When I add pod 'Web3' to my Podfile I get this error:

`[!] Unable to find a specification for Web3`

Could you provide a more detail instructions to install?

**Comment by Ybrin** [comment]
Hi @emiliomarin 

Thank you for your comment.

We just released version 0.1.0.

Please try again by first updating your pod repo

```
pod repo update
```

and then running `pod install` again after adding `pod 'Web3'` to your Podfile.

Also have a look through our new README where you can find helpful examples to get you started.

If you have any other questions, just ask. We are here to help.

**Comment by Ybrin** [comment]
Also, if you want to use the PromiseKit extensions like in the tutorial, you should add

```
pod 'Web3/PromiseKit'
```

to your Podfile and run `pod install` again.

**Comment by Ybrin** [comment]
Your problem should not exist any more. Please confirm this so we can close this issue.

**Comment by Ybrin** [comment]
I will close this issue for now. If you still have problems with the installation just reopen it.
