### ISSUE TITLE
Cannot extend eth send methods

### ISSUE THREAD

**Issue by pixelmatrix** [Boilertalk/Web3.swift#16]
I'm trying to extend the Eth module in my own app to include a couple of additional methods, but ran into an issue. Eth.properties is internal, and that's the only place where the provider and the rpcId are stored. One additional issue is that in the PromiseKit subspec, the Web3Response sealPromise method is fileprivate, so I can't easily add promise-based methods.

As a temporary workaround, I created an extension for Web3 itself which works fine, but it would be cleaner to just extend Eth.

**Comment by Ybrin** [comment]
You are right. `properties` should definitely be public. Not just in the `Eth` struct but also in `Net`.

I'm not quite sure about the `sealPromise` method. I am not completely satisfied with this `Web3Response` extension but if you think that's the right way for now you can definitely add it.

Please open a pull request with those fixes if you can. I will publish a bug fix release with them ASAP.

**Comment by pixelmatrix** [comment]
Thanks for the quick response. I've opened up #17 to fix it, and it works for me locally. I left the PromiseKit stuff out for now, since it sounds like maybe you're still thinking about the best way to handle that. Perhaps there could be a protocol and an extension for conformance that automatically adds a Promise return type.

**Comment by Ybrin** [comment]
You are right, I am not yet completely convinced of my implementation and don't really want to make it available until I am.

I will definitely think about how to implement a generic solution for sealing the promises and make it available in the public API.

**Comment by pixelmatrix** [comment]
Sounds great. Thanks for the quick response, and great work so far on the framework!
