### ISSUE TITLE
Ocean protocol startOrder method implementation

### ISSUE THREAD

**Issue by aburashima** [Boilertalk/Web3.swift#162]
Hello,
Can the Ocean protocol's startOrder() method be implemented in your library?
Please see for reference: https://github.com/oceanprotocol/contracts/blob/9e29194d910f28a4f0ef17ce6dc8a70741f63309/contracts/templates/ERC20Template.sol#L519
Could the Static Smart Contract pattern be used as a substitute for startOrder()?
Thank you in advance!

**Comment by koraykoska** [comment]
@aburashima You can create a static contract yourself or extend the ones we provide (see readme). Or you can use the dynamic ABI parser (see readme again) to call whichever method you want.
We don't integrate higher-level abstraction than ABI parsing into the library.

**Comment by koraykoska** [comment]
Please join the Telegram chat for further support (see link in readme).
