### ISSUE TITLE
String.hexBytes() suggestion

### ISSUE THREAD

**Issue by pixelmatrix** [Boilertalk/Web3.swift#26]
I've encountered a few instances where string.hexBytes() threw an error because the value was not divisible by 2. It looks like the root of the issue is that hex can actually be represented with or without a leading zero, and String.init(_:, radix:) returns the most compact format.

A quick example using the Swift console:

```
 > String(4095, radix: 16)
$R19: String = "fff"
 > 0xfff
$R20: Int = 4095
> 0x0fff
$R21: Int = 4095
```

Since you're iterating over the string in 2 character increments it makes sense that the string should be divisible by 2. My suggestion would be to append a zero if it's not already divisible by two instead of throwing an error so that it is more flexible.

**Comment by Ybrin** [comment]
Yes I think you are right. Omitting leading zeros is definitely allowed for hex numbers and it shouldn't be a problem to append it in our implementation.

**Comment by Ybrin** [comment]
Do you want to implement this or do you want me to do it?

**Comment by pixelmatrix** [comment]
I can do a quick PR later today. Do you want to target 0.2.0 or master?

**Comment by Ybrin** [comment]
0.2.0 please. I think I'm going to move the Contract ABI stuff to 0.3.0 and release 0.2.0 with the bug fixes and features we added until now...

**Comment by Ybrin** [comment]
The related PR was merged so I'm closing this.
