### ISSUE TITLE
Missing Web3+HTTPInitializer.swift

### ISSUE THREAD

**Issue by iBinh** [Boilertalk/Web3.swift#34]
I install via cocoapods and pod directory seem missing Web3+HTTPInitializer.swift and Web3HttpProvider.swift
so that    Web3(rpcURL: "https://mainnet.infura.io/<your_infura_id>") does not work

**Comment by Ybrin** [comment]
Please send me your Podfile, or at least the Web3 line in it.

**Comment by iBinh** [comment]
`target 'Test App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'SwiftyDropbox'
    pod 'Web3/PromiseKit'

end
`

**Comment by Ybrin** [comment]
Please change it to the following:

```

**Comment by Ybrin** [comment]
```
pod 'Web3'
pod 'Web3/PromiseKit'
```

**Comment by iBinh** [comment]
It works. Thank you!

**Comment by Ybrin** [comment]
Always install the normal `Web3` package and add extensions after that. That's the way we manage subspecs right now. I think I will add a section to the readme to clarify it...

**Comment by Ybrin** [comment]
I think this issue is resolved now.
