### ISSUE TITLE
Create and Import Accounts

### ISSUE THREAD

**Issue by GabCas** [Boilertalk/Web3.swift#46]
Is there a way to create and/or import accounts?
from: http://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#create
I'm looking for:
- web3.eth.accounts.create()
- web3.eth.accounts.privateKeyToAccount(privateKey);

**Comment by Ybrin** [comment]
Yes there is. You have to create a new private key with the default initializer of `EthereumPrivateKey` and the use [the keystore library](https://github.com/Boilertalk/Keystore.swift) to create a keystore 'account'.    
Please visit the keystore repository for examples. But to create the raw private key which you have to do first you can use Web3. Here is an example:

```Swift
import Web3

let privateKey = EthereumPrivateKey()
let privateKeyBytes = privateKey.rawPrivateKey       // Use this with the keystore.swift library to create your account.
```

**Comment by GabCas** [comment]
Thank you, that worked. I was able to create a keystore account and extract the private key.  
Is it normal that each step takes around 45 seconds? Granted, I'm using an iPhone 5 with iOS 10.

**Comment by Ybrin** [comment]
Hey @GabCas

Long keystore creation and private key extraction times are only normal in
debug builds. Once you build it for production (with speed optimizations,
which is default for iOS production builds) it should be 50 to 60 times
faster. I am already using it in a system which generates 'a few' per
second even on older iPhones.
