### ISSUE TITLE
How to get Error Code or Message?

### ISSUE THREAD

**Issue by voyage11** [Boilertalk/Web3.swift#67]
Hi,
I have been searching for a way to extract the code and message out from the error. 

For example:-
`Error: Error(code: -32000, message: "insufficient funds for gas * price + value")`

How can I get the Code and the Message?

**Comment by Ybrin** [comment]
If you have an instance of error you could do something like that:

```Swift
if let error = error as? RPCResponse<EthereumData>.Error {
    print(error.code)
    print(error.message)
}
```

**Comment by Ybrin** [comment]
Having to provide the generic type for RPCResponse on your own is really not great. I think we should change the Error to a non-subtype.

**Comment by Ybrin** [comment]
Btw, my example is only possible with version 0.3.1 which was released just today...

**Comment by voyage11** [comment]
I tested. It worked great! Thanks @Ybrin !
