### ISSUE TITLE
Crash in EthereumAddress. Need help!

### ISSUE THREAD

**Issue by pushkin2023** [Boilertalk/Web3.swift#83]
I am using in my project web3 either as pod or with carthage and when i create a EthereumAddress object the app crashes with  EXC_BAD_ACCESS (code=1, address=0x5)  on line: 'let hash = SHA3(variant: .keccak256).calculate(for: Array(hex.lowercased().utf8))'
Has anybody issues with this or can help me resolve the crash? Thanks.

**Comment by koraykoska** [comment]
@pushkin2023 Can you reproduce this in an example project and push it to Github so I can check? Also tell me on which iPhone Model it happens please.

**Comment by koraykoska** [comment]
@pushkin2023 I will close this. Let me know if you still need help in the Telegram Group. https://t.me/web3_swift
