### ISSUE TITLE
Can not run unit tests

### ISSUE THREAD

**Issue by sche** [Boilertalk/Web3.swift#85]
I tried to:
1) run 'pod install' in Examples folder.
2) open Web3.xcworkspace
3) run unit tests for Web3-Example
=> fails

Do I do smth wrong?

**Comment by koraykoska** [comment]
@sche I have made a big mistake with the unit tests by not mocking the server requests and unfortunately Infura decided to break their API keys.
Try to only run the local tests, that should work.
You can also generate a new Infura key and try the tests again or,

if you dare, create a mock for an Ethereum node so we can finally write tests without Infura.

**Comment by koraykoska** [comment]
@sche So don't run `Web3Tests/Web3HttpTests.swift` as this file contains Infura dependencies. Everything else should work. If not let me know the error please.

**Comment by koraykoska** [comment]
I fixed this.

The next major version of Web3.swift will not support anything other than SPM.

I made this decision as it becomes more and more prevalent that Cocoapods and Carthage are not maintained any more.
There are so many issues with Cocoapods that I don't even want to get started with it.
But as a matter of fact: Cocoapods is not really maintained any longer. And for anyone using XCode 11 and above, you can simply add SPM Packages even if you are still using Cocoapods. Just add them into your .xcworkspace.

SPM will and should replace Cocoapods in all projects. There are simply no benefits and much more hassle using Cocoapods as of today.
The world is changing. Especially the Software world. We have to change with it.

The tests are working again in the master branch, which will be released this week. Just try it with `swift test`
